[package]
name = "biblatex2html"
version = "0.1.0"
edition = "2024"

[dependencies]
biblatex = "0.11.0"
clap = { version = "4.5.53", features = ["derive"] }
minijinja = "2.12.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["serde_derive"] }
